### ISSUE TITLE
Recovery from RabbitMQ Exceptions

### ISSUE THREAD

**Issue by josecelano** [SimpleBus/RabbitMQBundle#2] opened 2015-03-04 13:17 UTC
I have seen that you do not catch any exception from RabbitMQ library:

https://github.com/SimpleBus/RabbitMQBundle/blob/master/src/RabbitMQPublisher.php#L37

I suppose there are some Exceptions that can be thrown trying to publish a message in the queue: 

https://github.com/videlalvaro/php-amqplib/tree/82ece62a68d8a82214c49c415ddc9df770c25ce9/PhpAmqpLib/Exception

Do you think they could be handled inside your library or maybe it´s better to treat them at higher app level, for example when you inject the command in the bus?

I suppose most of MQ systems have a high-availability mode so connection problems should not be a problem to treat at client side, but I have found this library for exactly that purpose:

https://github.com/jhalterman/lyra

In case I want to implement a solution in my app I have thougth I could catch the exception and store the command in a database and re-try to publish it in the queue later. I could do that in my app but do you think it would be useful to be in your library?

Which one of these solutions do you think is better?:

**Solution1** (app handles them)
- Try/Catch command bus handle method and store the command in the database to be re-published later with a cronjob.

**Solution2** (RabbitMQBundle handles them ussing extra middleware)
- Add a new middleware to the asynchronous bus: SimpleBus/MySQLBundle or more generic SimpleBus/DatabaseBundle. Messages are stored always there before trying to publish them. Then we catch exceptions inside RabbitMQBundle. If there is an Exception then the message will be obtained from database later to be re-published. This solution is a kind of extra realibility plugin for RabbitMQBundle.

**Solution 3** (server responsability)
- RabbitMQ is awalys available (using load balancer or any other RabbitMQ high-availability feature).

Any other suggestion?

Finally,  what about having any kind of persistence for messages?. You could add a database implementation for asynchronous buses. I suppose it could use the same interface publiser/consumer. This Sonata Project:

http://sonata-project.org/bundles/notification/master/doc/reference/usage.html

allows to use database or RabbitMQ. I think it is a good idea because you can start using database and as you need more scalability or flexibility you can go with RabbitMQ.

**Comment by josecelano** [comment] 2015-03-04 13:30
I have asked something similar in the library you are using at low level:

https://github.com/videlalvaro/php-amqplib/issues/253#issuecomment-77150075

and @michaelklishin has told me to use HAproxy in front of RabbitMQ cluster. This way application has not care about server availavility by I that is a more expensive solution.

**Comment by matthiasnoback** [comment] 2015-03-04 15:23
That's correct, I don't :) I don't have the solution for this yet. I'm in doubt how much I should implement for this, since the nature of SimpleBus is that it's simple and anything specific that the user wants, should be developed by them I think. Still, some general recovery mechanism might be good. I have to think about this.

**Comment by cmodijk** [comment] 2015-03-10 21:49
There is more to it then only RabbitMQ Exceptions. What if a command throws one? If I saw it correctly know the consumer will die? 

I'm also interested in if anybody have any solution for the next problems. We are currently using SimpleBus with our own RabbitMQ integration but because of the fact that Symfony uses a container and we could inject a lot of fun stuff.
* Problem 1: You will get to some point in time that you mysql connection is gone `General error: 2006 MySQL server has gone away `. 
* Problem 2: Another problem is the fact that doctrine closes the EntityManager if it revives an exception from the database (like a duplicate exception). And al the commands after that command wil fail. 
* Problem 3: Because of the fact that you could send commands synchronously and asynchronously you don't think about optimizing things. For instance the EntityManager keeps a records of al the objects that are created but maybe this needs to be cleared after every consumed message  
  * We deal with this by sending a event after every consumed message and have a listener clear al the ObjectManagers
  * https://github.com/JCID/RabbitMQSimpleBusBridge/blob/master/src/EventDispatcher/Listener/DoctrineOrmPostMessageEventListener.php#L30-L34

This is an interesting artikel about the subject
* http://blog.vandenbrand.org/2015/01/09/symfony2-and-rabbitmq-lessons-learned/

**Comment by matthiasnoback** [comment] 2015-03-11 07:42
Interesting issues here. I've worked on some long-running Symfony applications and the problems you mention (as well as those from the article by Richard) are very familiar. I solved them in the same way as you did by the way. Some remarks:

- These are not RabbitMQ-specific things. I'm thinking about creating a separate project to make creating long-running Symfony applications easier.
- Closing the PDO connection was sufficient in my case to prevent these timeouts from occurring.
- You have to clear the entity manager(s) after each handled message, because other workers also keep entities in memory, which will soon result in failing transactions.
- You may also need to use Doctrine's optimistic locking to prevent command handlers from making changes to the same entity.
- The current version of SimpleBus can recover from (Doctrine) exceptions. This means you can already handle messages in a loop, even though some of them fail.
- In its current implementation the consumer just stops when an exception occurs. This is not really useful, so instead I will make it log the failure and let it keep consuming messages.
- Instead of hard-coding this behaviour I think it would make a lot more sense to have some kind of error handler mechanism, which is extensible by users, who may then store the message somehow and retry it later.

**Comment by matthiasnoback** [comment] 2015-03-11 09:30
I've just introduced the concept of an error handler in the bundle: http://simplebus.github.io/RabbitMQBundle/doc/error_handling.html This is at least an extension point for user-land error handling code :)

**Comment by matthiasnoback** [comment] 2015-03-11 10:05
Wait, I'm removing the error handling part right now, going for events :)

**Comment by matthiasnoback** [comment] 2015-03-11 10:26
So, there you go: http://simplebus.github.io/RabbitMQBundle/doc/events.html Events for message that were handled successfully and unsuccessfully. This means you can also hook into these events to reset the state of the system (i.e. close connections, clear entity managers, etc.). I consider it highly likely that I will at some point publish a project that offers several of these "cleanup" tools for Doctrine DBAL, ORM, etc.

**Comment by matthiasnoback** [comment] 2015-03-11 14:11
Hi everyone - now that you can recover from exceptions, do you agree that we can close this issue? SimpleBus still tries to be very simple and not offer solutions for every situation, but now the bundle has some useful extension points, which would allow users to step in at some crucial moments. What do you think?

**Comment by josecelano** [comment] 2015-03-11 14:22
I suppose it is OK and you can close this issue. I will upgrade my app. For the time being I am going to add an event listener for that event and log the problem. I suppose in the future I can store the messages in a database and try to process them again (if the problem is for exampleMQ server down).

**Comment by matthiasnoback** [comment] 2015-03-11 14:24
Yep, it should be quite easy to also store the event in the database (I think you can just use PHPs native `serialize()` function to serialize the entire message and later hand it to the consumer again.

So thanks for your input, this will be it for now! :)

**Closed by matthiasnoback** 2015-03-11 14:24 UTC

**Comment by cmodijk** [comment] 2015-03-11 15:49
Cool! I think it's a great way!

**Comment by matthiasnoback** [comment] 2015-03-11 21:39
I created a POC library/bundle containing many of the above-mentioned clean up tasks for long running commands: https://github.com/LongRunning/LongRunning It will automatically register cleaners for Doctrine ORM, Doctrine DBAL and SimpleBus/RabbitMQ when the respective bundles are enabled.

**Comment by cmodijk** [comment] 2015-03-12 06:26
You-are-fast!

How do you handle the following we directly inject the EntityManager into our command handlers. And when the are getting closed you cannot use reopen them. The resetManager only kills al the existing EntityManager and remove the entity manager in the Container but it cannot reset the already injected ones. The only way i found was to always inject the `ManagerRegistry` instead.

I don't think it is possible but I would really like to reset the complete container except for the services needed for the long running process/RabbitMQ. 

I never new that when you close the DBAL connection it will reopen it on the next query i think thats a create option to solve the `General error: 2006 MySQL server has gone away` error.

**Comment by matthiasnoback** [comment] 2015-03-12 08:09
That's right, you can't inject the EntityManager anywhere, only the registry. For command handlers I only use repositories, which consist of an explicit interface, and get the ManagerRegistry injected:

```php
class DoctrineUserRepository implements UserRepository
{
    public function __construct(ManagerRegistry $managerRegistry)
    {
        ...
    }
    public function add(User $user)
    {
        $this->entityManager()->persist($user);
    }

    private function entityManager()
    {
        return $this->managerRegistry->getManager(User::class);
    }
}
```

Closing the db connection helped solve the "gone away" issues that we were facing last year.

**Comment by cmodijk** [comment] 2015-03-12 09:17
Hmmm very interesting!

**Comment by guilleferrer** [comment] 2016-12-15 11:09
+1

**Comment by cmodijk** [comment] 2016-12-17 12:37
Hi @guilleferrer i see you +1 here but the issue is closed for a long time now. Can i answer an questions you have?
